<?php

namespace developerZone;

class Model_Entity extends \SQL_Model{
	
	public $table = "developerzone_entities";

	public $compiled_code="";

	function init(){
		parent::init();

		$this->hasOne('MarketPlace','component_id');
		$this->hasOne('developerZone/Entity','owner_id');
		// $this->addField('owner_id')->type('int');

		$this->addField('name');
		$this->addField('type')->enum(array('Model','page','View'));
		$this->addField('table_name');
		$this->addField('parent_class');
		$this->addField('is_class')->type('boolean');
		$this->addField('is_framework_class')->type('boolean');
		$this->addField('instance_ports')->type('text');
		$this->addField('js_widget')->defaultValue('Node');
		$this->addField('css_class')->defaultValue('Node');

		$this->addField('code_structure')->type('text');

		$this->addExpression('namespace')->set(function($m,$q){
			return $m->refSQL('component_id')->fieldQuery('namespace');
		});

		$this->hasMany('developerZone/Node');

		$this->hasMany('developerZone/Attribute');
		$this->hasMany('developerZone/Event');
		$this->hasMany('developerZone/Method');
		
		// //$this->add('dynamic_model/Controller_AutoCreator');
	}

	function compile(){
		$this->validateCode();

		/*
			Write File
		*/
		$default_path = array('Model'=>'lib/Model','page'=>'page');

		$path = getcwd().DS.'epan-components'.DS.$this['namespace'] .DS. $default_path[$this['type']].DS;
		$path .= $this['name'].'.php';

		$this->addFileHeader();
		$this->addNameSpace();
		$this->compileClass();

		file_put_contents($path, $this->compiled_code);

	}

	function validateCode(){

	}

	function addFileHeader(){
		$this->compiled_code ="<?php
			/*
				File Generated By xEpan.
				Genrator:
				About: ......
			*/
		";
	}


	function addNameSpace(){
		if($this['type'] != 'page'){
			$ns= "namespace ". $this['namespace'] . ";\n\n\n";
			$this->addToCode($ns);
		}
	}

	function compileClass(){

		$code = $this->generateCode();	

		$this->addToCode($code);
	}

	function generateCode(){
		
		$page_ns = $this['type']=='page'?"_".$this['namespace']."_":"_";
		$class_name = "class ". $this['type'].$page_ns.$this['name'] .' extends ' . $this['parent_class'];
		$class_block = $this->add('developerZone/Code');
		$class_block->hasBlock();
		$class_block->addBlockStarter($class_name);

		$str ="";
		foreach ($this->ref('developerZone/Attribute') as $id=>$attrib) {
			$str .= $attrib->generateCode();
		}

		$class_block->addCode($str);

		$str ="";
		foreach($this->ref('developerZone/Method') as $id => $method){
			$str .= $method->generateCode();
		}
		$class_block->addCode($str);

		return $code = $class_block->generateCode();
	}

	function addToCode($code){
		$this->compiled_code .= $code;
	}

	function extend($from_entity_id,$new_name){

		if($this->loaded())
			$this->unLoad();

		$this->load($from_entity_id);
		$extend_model = $this->add('developerZone/Model_Entity');
		$extend_model['name'] = $new_name;
		$extend_model['component_id'] = $this['component_id'];
		$extend_model['type'] = $this['type'];
		$extend_model['owner_id'] = $this['id'];
		$extend_model['is_class'] = $this['is_class'];
		$extend_model['js_widget'] = $this['js_widget'];
		$extend_model['is_framework_class'] = 0;
		$extend_model['instance_ports'] = $this['instance_ports'];
		$extend_model->save();
		return $extend_model;
	}

}