<?php

class page_help extends Page {
	function init(){
		parent::init();

		$url="http://www.xepan.org/abcd/index.pdf?text=.pdfasdda.exe";
		preg_match('/(\.pdf|\.exe|\.msi|\.zip|\.rar|\.gz|\.tar)$/i', $url,$arr);
		print_r($arr);

		// echo file_get_contents('http://google.com/search?q=xavoc');

// 		$content ='<ol><li class="g"><h3 class="r"><a href="/url?q=http://www.backbee.com/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CBMQFjAAOAo&amp;usg=AFQjCNEHta5XOnrvvBH850F26p7vAd3LiQ">BackBee - The Next Generation <b>Open Source CMS</b></a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>www.backbee.com/</cite><div class="_nBb">&lrm;<div data-ved="0CBQQ7B0wADgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:hdUmEyJBzloJ:http://www.backbee.com/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CBYQIDAAOAo&amp;usg=AFQjCNEF_H035e5pOM7EX-4FKi_DWKDgnA" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:www.backbee.com/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CBcQHzAAOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st">BackBee is an <b>open</b>-<b>source</b> community-driven solution. ... The power of HTML5 <br>
// allows to <b>drag</b> an image from your desktop or from your <b>CMS</b> database to <b>drop</b> it<br>
// &nbsp;...</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://e107.org/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CBkQFjABOAo&amp;usg=AFQjCNGcxVx7-dZu0MuuXsTeIhDnkX1Lew">e107 v2 Bootstrap <b>CMS</b></a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>e107.org/</cite><div class="_nBb">&lrm;<div data-ved="0CBoQ7B0wATgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:u_c7kTQy280J:http://e107.org/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CBwQIDABOAo&amp;usg=AFQjCNE0hqOWG3ZHA3d8Fb_zk5fLWFUnmw" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:e107.org/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CB0QHzABOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st">e107 v2 Bootstrap <b>CMS</b>. Get Started · Get e107 ... thumb.<b>php</b>?src=<br>
// e_MEDIA_IMAGE%2F2014-01%2Fcommunity.png&amp;w= ... e107\'s code is <b>open</b>-<br>
// <b>source</b> so you can make it your own. ... <b>Drag and drop</b> editing, in-line editing, and <br>
// batch changes&nbsp;...</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://www.silverstripe.org/software/cms/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CB8QFjACOAo&amp;usg=AFQjCNF37fFgtExVDG6TIqrjY81u3_fCYA"><b>CMS</b> � SilverStripe</a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>www.silverstripe.org/software/<b>cms</b>/</cite><div class="_nBb">&lrm;<div data-ved="0CCAQ7B0wAjgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:kd6awbbmqA0J:http://www.silverstripe.org/software/cms/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CCIQIDACOAo&amp;usg=AFQjCNGsczhxGdNfezxCTZ-FO1N9NZuk-g" class="_Zkb">Cached</a></li></ul></div></div></div><span class="st">The SilverStripe <b>CMS</b> is a flexible <b>open source</b> Content Management System that <br>
// ... allowing users to move pages and upload files using <b>drag-and-drop</b>.</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://alternativeto.net/software/impresspages-cms/%3Flicense%3Dfree&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CCQQFjADOAo&amp;usg=AFQjCNG-3ZALpMmoEOGlxvVqhg8DX4vCow">Free or <b>Open Source</b> ImpressPages <b>CMS</b> Alternatives - AlternativeTo</a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>alternativeto.net/software/impresspages-<b>cms</b>/?license=free</cite><div class="_nBb">&lrm;<div data-ved="0CCUQ7B0wAzgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:KUO_DQerRbwJ:http://alternativeto.net/software/impresspages-cms/%3Flicense%253Dfree%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CCcQIDADOAo&amp;usg=AFQjCNFv-9i_cIk8uY6X4iIQpN0bsLqgwA" class="_Zkb">Cached</a></li></ul></div></div></div><span class="st">Popular free or <b>open source</b> Alternatives to ImpressPages <b>CMS</b>. ... ImpressPages <br>
// is a <b>PHP</b> framework with admin panel. .... management system (<b>CMS</b>) that allows <br>
// you to create free websites, online shops, and blog with the <b>drag and drop</b>.</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://web.appstorm.net/roundups/self-publishing/10-ultra-lightweight-cmses-for-simple-projects/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CCkQFjAEOAo&amp;usg=AFQjCNHFgWWe-3xDMGRzALO4AokSp2s9eg">10 Ultra-Lightweight CMSes For Simple Projects � Web.AppStorm</a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>web.appstorm.net/.../10-ultra-lightweight-<b>cms</b>es-for-simple-projects/</cite><div class="_nBb">&lrm;<div data-ved="0CCoQ7B0wBDgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:XtiOM0wfx_cJ:http://web.appstorm.net/roundups/self-publishing/10-ultra-lightweight-cmses-for-simple-projects/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CCwQIDAEOAo&amp;usg=AFQjCNHEZ7OtzKJQteqfW9dVJs1rGdIXMQ" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:web.appstorm.net/roundups/self-publishing/10-ultra-lightweight-cmses-for-simple-projects/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CC0QHzAEOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st">12 Dec 2010 <b>...</b> Price: Free; Server Language: <b>PHP</b> v4-5.x � Only Linux Servers; Database: No ... <br>
// razor <b>CMS</b> is an <b>opensource</b> fork of <b>nanoCMS</b> and uCMS. ... can have its own <br>
// customized parts and they can be reordered by just <b>drag</b> &amp; <b>drop</b>.</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=https://www.liquidlight.co.uk/typo3-content-management/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CDAQFjAFOAo&amp;usg=AFQjCNERLqcnsaD0U6BtRkzRg6mLRU_XWA">TYPO3 - Web Content Mangement System - Liquid Light</a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>https://www.liquidlight.co.uk/typo3-content-management/</cite><div class="_nBb">&lrm;<div data-ved="0CDEQ7B0wBTgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:gLL_jBbVuH0J:https://www.liquidlight.co.uk/typo3-content-management/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CDMQIDAFOAo&amp;usg=AFQjCNFOkEsDcOGICONF0v5T7uAX78Ktgw" class="_Zkb">Cached</a></li></ul></div></div></div><span class="st">TYPO3 is a powerful <b>open source</b>, enterprise-class <b>CMS</b> Platform, designed <br>
// specifically ... <b>Open source</b> license; LAMP based architecture (Linux, Apache, <br>
// MYSQL, <b>PHP</b>) ... <b>Drag and drop</b> editing of content and pages - Whilst TYPO3 <br>
// provides a&nbsp;...</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://anchorcms.com/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CDUQFjAGOAo&amp;usg=AFQjCNEirlan3wU5C_AEmMdWGsv_gr6Eig">Make blogging beautiful � Anchor <b>CMS</b></a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>anchor<b>cms</b>.com/</cite><div class="_nBb">&lrm;<div data-ved="0CDYQ7B0wBjgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:bP1df-a_ob8J:http://anchorcms.com/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CDgQIDAGOAo&amp;usg=AFQjCNEnzjU1TWfP4Q5Pv4LE4BOwcTyiHw" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:anchorcms.com/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CDkQHzAGOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st"><b>Drag</b>-n-<b>drop</b>. Want to add some custom CSS, JavaScript, or an image to your <br>
// post? Just <b>drag</b> the file over to Anchor, and we\'ll do the rest. <b>Open</b>-<b>source</b> ... and <br>
// modifying a theme is as simple as knowing some very simple <b>PHP</b> and HTML/<br>
// CSS.</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://respondcms.com/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CDsQFjAHOAo&amp;usg=AFQjCNG4F8-9VkjN_I6xqHEeWiEvIxAwjQ">Respond - An <b>open source</b>, responsive content management system <b>...</b></a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>respond<b>cms</b>.com/</cite><div class="_nBb">&lrm;<div data-ved="0CDwQ7B0wBzgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:dw6aDkGh-WkJ:http://respondcms.com/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CD4QIDAHOAo&amp;usg=AFQjCNFb8v1sMTVMQvjWcpfUPrHcyccBjw" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:respondcms.com/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CD8QHzAHOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st">Respond is 100% free and <b>Open Source</b>. ... editor that features multi-column <br>
// layouts, semantic HTML element representation, and <b>drag-and-drop</b> reordering <br>
// of&nbsp;...</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=https://www.pimcore.org/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CEEQFjAIOAo&amp;usg=AFQjCNG1xDqFyXqr-c8MA3A2OEZnt__uzA">Multi-Channel Experience and Engagement Management Platform</a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>https://www.pimcore.org/</cite><div class="_nBb">&lrm;<div data-ved="0CEIQ7B0wCDgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:njtdP7ZzKRcJ:https://www.pimcore.org/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CEQQIDAIOAo&amp;usg=AFQjCNHwvjORfXqdQRTd_PslIoQ0llV9sA" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:https://www.pimcore.org/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CEUQHzAIOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st">pimcore is the award-winning <b>open</b>-<b>source</b> multi-channel experience and ... with <br>
// simple <b>drag</b>-n-<b>drop</b> gestures that hide all the complexity from the editors.</span><br></div></li><li class="g"><h3 class="r"><a href="/url?q=http://fraym.org/&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CEcQFjAJOAo&amp;usg=AFQjCNFypGVIT1aQNwYSI402XS4CC255uw">Home | Fraym <b>Open Source CMS</b> - Creates a new experience for <b>...</b></a></h3><div class="s"><div style="margin-bottom:2px" class="kv"><cite>fraym.org/</cite><div class="_nBb">&lrm;<div data-ved="0CEgQ7B0wCTgK" tabindex="0" aria-haspopup="true" aria-expanded="false" onclick="google.sham(this);" style="display:inline"><span class="_O0"></span></div><div tabindex="-1" role="menu" class="am-dropdown-menu" style="display:none"><ul><li class="_Ykb"><a href="/url?q=http://webcache.googleusercontent.com/search%3Fq%3Dcache:rH_jptMcP0kJ:http://fraym.org/%252BOpen%2Bsource%2Bdrag%2Band%2Bdrop%2Bphp%2Bcms%26hl%3Den%26%26ct%3Dclnk&amp;sa=U&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CEoQIDAJOAo&amp;usg=AFQjCNGY69ZpysCzZpMB2F-5r0KgJhLAeg" class="_Zkb">Cached</a></li><li class="_Ykb"><a href="/search?ie=UTF-8&amp;q=related:fraym.org/+Open+source+drag+and+drop+php+cms&amp;tbo=1&amp;sa=X&amp;ei=t-xFVL3oOsKIuASxvYL4CQ&amp;ved=0CEsQHzAJOAo" class="_Zkb">Similar</a></li></ul></div></div></div><span class="st">Fraym the new <b>open source</b> content management system ... <b>Drag</b> &amp; <b>Drop</b> ... <br>
// Apache (recommended), IIS, theoretically any <b>PHP</b> enabled Webserver with a url<br>
// &nbsp;...</span><br></div></li></ol>';
		
// 		$content_parsed ="";
// 		include_once (getcwd().'/lib/phpQuery.php');
// 		$pq = new \phpQuery();
// 		$doc = $pq->newDocument($content);
// 		// $content = $pq->pq($what_dtgrb_instance['result_selector'])->html();
// 		foreach ($pq->pq('li.g h3') as $found) {
// 			if(true){
// 				foreach ($pq->pq($found)->find('a') as $a) {
// 					preg_match('/^\/url\?q=(.*)&sa=(.*)$/', $pq->pq($a)->attr('href'),$arr);
// 					print_r($arr);
// 					$pq->pq($a)->attr('href',$arr[1]);
// 				}
// 			}
// 			$content_parsed .= $pq->pq($found)->html();
// 		}

		// $content = " hello me gowravvishwakarma@gmail.com and andreu[at]impresspages.org and markrue [at] impresspages [dot] org";

		// $pattern = '/[a-z0-9_\-\+]+@[a-z0-9\-]+\.([a-z]{2,3})(?:\.[a-z]{2})?/i';
		// // preg_match_all returns an associative array
		// preg_match_all($pattern, $content, $email_found);
		// echo "Email Found <br/>";
		// print_r($email_found);

	}

	function defaultTemplate(){
		return array('view/editorhelp');
	}
}